services:
  hoge_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: hoge_container
    container_name: hoge_container
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]